import { expect, it } from 'vitest';
import { quietFile } from './quiet.ts';
import type { DocRef } from '../platforms/types.ts';

const code = (path: string, status: DocRef['status'] = 'modified', oldPath = path): DocRef => ({ path, oldPath, status, kind: 'code' });
const label = (doc: DocRef, base = 'a\n', head = 'b\n') => quietFile(doc, { base, head })?.label ?? null;

it('folds files a package manager or build wrote, wherever they live', () => {
  for (const path of ['package-lock.json', 'web/yarn.lock', 'pnpm-lock.yaml', 'Cargo.lock', 'Gemfile.lock', 'poetry.lock', 'go.sum'])
    expect(label(code(path)), path).toBe('Lockfile');
  expect(label(code('public/app.min.js'))).toBe('Minified');
  expect(label(code('styles/site-min.css'))).toBe('Minified');
  expect(label(code('vendor/acme/client.php'))).toBe('Vendored');
  expect(label(code('third_party/zlib/zlib.h'))).toBe('Vendored');
  expect(label(code('packages/ui/dist/index.js'))).toBe('Build output');
  for (const path of ['api/service.pb.go', 'proto/service_pb2.py', 'lib/user.g.dart', 'src/schema.generated.ts', 'src/routes.gen.ts'])
    expect(label(code(path)), path).toBe('Generated');
});

it('folds a file that says it was generated, but only in its first lines', () => {
  expect(label(code('src/client.ts'), '', '// Code generated by openapi. DO NOT EDIT.\nexport {};\n')).toBe('Generated');
  expect(label(code('src/client.ts'), '/* @generated */\nold();\n', '/* @generated */\nnew();\n')).toBe('Generated');
  expect(label(code('src/schema.py', 'removed'), '# This file is automatically generated.\nx = 1\n', '')).toBe('Generated');
  const late = `${'line();\n'.repeat(5)}// DO NOT EDIT this list by hand\n`;
  expect(label(code('src/list.ts'), 'a();\n', late)).toBeNull();
});

it('folds whitespace-only changes, except where indentation is meaning', () => {
  const wrapped = quietFile(code('src/limits.ts'), { base: 'const limit = { perMinute: 100 };\n', head: 'const limit = {\n  perMinute: 100,\n};\n' });
  expect(wrapped).toBeNull();
  const spaced = quietFile(code('src/limits.ts'), { base: 'if (a) {\n    run();\n}\n', head: 'if (a) {\n  run();\n}\n' });
  expect(spaced).toStrictEqual({ label: 'Whitespace only', reason: 'Only spaces, tabs or line breaks changed.', added: 1, removed: 1 });
  expect(label(code('src/limits.ts'), 'return x;\n', 'returnx;\n')).toBeNull();
  for (const path of ['app.py', 'deploy.yaml', 'Makefile', 'build/rules.mk']) expect(label(code(path), 'a:\n    b\n', 'a:\n  b\n'), path).toBeNull();
  expect(label(code('src/new.ts', 'added'), '', 'x\n')).toBeNull();
  expect(label(code('src/gone.ts', 'removed'), 'x\n', '')).toBeNull();
});

it('folds a renamed file whose text did not change, document or code, and counts what changed', () => {
  const renamed: DocRef = { path: 'docs/guide.md', oldPath: 'docs/old-guide.md', status: 'renamed' };
  expect(quietFile(renamed, { base: '# Guide\n', head: '# Guide\n' })).toStrictEqual({
    label: 'Renamed',
    reason: 'Renamed from docs/old-guide.md, text unchanged.',
    added: 0,
    removed: 0,
  });
  expect(label(renamed, '# Guide\n', '# Better guide\n')).toBeNull();
  expect(label({ ...renamed, path: 'vendor/docs/guide.md' })).toBe('Vendored');
  expect(label({ path: 'docs/guide.md', oldPath: 'docs/guide.md', status: 'modified' })).toBeNull();
  expect(quietFile(code('package-lock.json'), { base: 'a\r\nb\r\nc\r\n', head: 'a\nB\nC\nd' })).toMatchObject({ added: 3, removed: 2 });
  expect(label(code('src/review.ts'))).toBeNull();
});
