apiVersion: apps/v1
kind: Deployment
metadata:
  name: renderer
  namespace: reviews
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  namespace: reviews
spec:
  replicas: 1
